apiVersion: v1
kind: Namespace
metadata:
  name: gateway

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: gateway
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://10.2.101.99:30080;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: nginx
          image: nginx:1.29
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
